import { User, Post, Story, NotificationItem } from '../types';

export const INITIAL_USERS: Record<string, User> = {
  'user-me': {
    id: 'user-me',
    name: 'Sarah Jenkins',
    handle: 'sarahjenkins',
    avatar: '/zensocial_logo.png',
    coverImage: 'https://images.unsplash.com/photo-1707343843437-caacff5cfa74?w=1200&auto=format&fit=crop&q=80',
    role: 'Civic Journalist & Public Policy Fellow',
    organization: 'Global Affairs Review',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    category: 'journalist',
    verified: true,
    bio: 'Covering international diplomacy, civic technology, youth voter engagement, and academic research partnerships.',
    followersCount: 14820,
    followingCount: 342,
    postsCount: 86,
    website: 'https://globalaffairs.org',
    isFollowing: false,
  },
  'user-turkey': {
    id: 'user-turkey',
    name: 'Presidency of the Republic of Türkiye',
    handle: 'tcbestepe',
    avatar: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/turkey_presidential_address_1791116189647.jpg',
    role: 'Head of State · Republic of Türkiye',
    organization: 'Government of Türkiye',
    country: 'Türkiye',
    countryFlag: '🇹🇷',
    category: 'politician',
    verified: true,
    bio: 'Official ZenSocial account of the Presidency of the Republic of Türkiye. Sharing official speeches, diplomatic engagements, and national development initiatives.',
    followersCount: 3840000,
    followingCount: 12,
    postsCount: 512,
    website: 'https://www.tccb.gov.tr',
    isFollowing: true,
  },
  'user-pakistan': {
    id: 'user-pakistan',
    name: 'Government of Pakistan',
    handle: 'govtofpakistan',
    avatar: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/pakistan_state_summit_1791116208095.jpg',
    role: 'Prime Minister Office · Islamic Republic of Pakistan',
    organization: 'Government of Pakistan',
    country: 'Pakistan',
    countryFlag: '🇵🇰',
    category: 'politician',
    verified: true,
    bio: 'Official communications from the Prime Minister Office of Pakistan. Economic corridors, youth empowerment programs, climate diplomacy, and international partnerships.',
    followersCount: 2920000,
    followingCount: 24,
    postsCount: 420,
    website: 'https://pmo.gov.pk',
    isFollowing: true,
  },
  'user-oxford': {
    id: 'user-oxford',
    name: 'University of Oxford',
    handle: 'oxford_uni',
    avatar: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/university_campus_graduates_1791116224809.jpg',
    role: 'Collegiate Research University',
    organization: 'University of Oxford',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    category: 'education',
    verified: true,
    bio: 'Leading the world in research, collegiate education, and global scientific collaboration. Empowering the next generation of scholars.',
    followersCount: 1250000,
    followingCount: 110,
    postsCount: 890,
    website: 'https://www.ox.ac.uk',
    isFollowing: true,
  },
  'user-robotics': {
    id: 'user-robotics',
    name: 'BlueWave Robotics & CleanTech',
    handle: 'bluewave_robotics',
    avatar: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/tech_enterprise_innovation_1791116239383.jpg',
    role: 'Enterprise AI & Clean Automation',
    organization: 'BlueWave Corp',
    country: 'Global',
    countryFlag: '🌐',
    category: 'business',
    verified: true,
    bio: 'Pioneering zero-emission autonomous industrial robots and next-generation renewable grid intelligence systems.',
    followersCount: 412000,
    followingCount: 89,
    postsCount: 145,
    website: 'https://bluewaverobotics.com',
    isFollowing: false,
  },
  'user-lums': {
    id: 'user-lums',
    name: 'LUMS Official',
    handle: 'lums_official',
    avatar: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80',
    role: 'Premier Research & Business University',
    organization: 'Lahore University of Management Sciences',
    country: 'Pakistan',
    countryFlag: '🇵🇰',
    category: 'education',
    verified: true,
    bio: 'A premier national university in Pakistan, fostering innovative leaders, scientific researchers, and public entrepreneurs.',
    followersCount: 380000,
    followingCount: 65,
    postsCount: 310,
    website: 'https://lums.edu.pk',
    isFollowing: false,
  },
  'user-tariq': {
    id: 'user-tariq',
    name: 'Tariq Mansoor',
    handle: 'tariq_civic',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&auto=format&fit=crop&q=80',
    role: 'Student Representative & Youth Voter Organizer',
    organization: 'Youth Civic Forum',
    country: 'Pakistan',
    countryFlag: '🇵🇰',
    category: 'citizen',
    verified: false,
    bio: 'Economics & Political Science student. Coordinating voter awareness drives across universities and college student councils.',
    followersCount: 8400,
    followingCount: 420,
    postsCount: 64,
    website: 'https://youthcivicforum.org',
    isFollowing: false,
  }
};

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-turkey-1',
    authorId: 'user-turkey',
    author: INITIAL_USERS['user-turkey'],
    content: 'Today at the Presidential Complex in Ankara, we addressed our nation and our international partners regarding the new comprehensive Mediterranean Energy & Green Trade Accord. \n\n"Türkiye will continue to serve as a bridge of peace, economic stability, and shared prosperity across Europe, Asia, and the Middle East." \n\nWe stand firmly committed to supporting our students with nationwide zero-interest startup grants and modern educational campus expansions.',
    timestamp: '2 hours ago',
    createdAt: Date.now() - 2 * 60 * 60 * 1000,
    audience: 'public',
    categoryLabel: 'Official Presidential Address',
    imageUrl: '/src/assets/images/turkey_presidential_address_1791116189647.jpg',
    speechDetails: {
      location: 'Presidential Complex, Ankara',
      event: 'Annual Diplomatic Corps & Civic Leaders Assembly',
      transcriptUrl: 'https://www.tccb.gov.tr/speeches/2026-accord',
    },
    likesCount: 28400,
    userReaction: 'like',
    commentsCount: 1420,
    sharesCount: 3950,
    hashtags: ['#Turkiye', '#Diplomacy', '#GreenEconomy', '#YouthDevelopment'],
    pinned: true,
    comments: [
      {
        id: 'c1',
        userId: 'user-me',
        user: INITIAL_USERS['user-me'],
        content: 'Crucial emphasis on educational startup grants alongside regional energy accords. How will students in regional colleges apply for the incubation funds?',
        timestamp: '1 hour ago',
        likesCount: 64,
        isLiked: true,
        replies: [
          {
            id: 'c1-1',
            userId: 'user-turkey',
            user: INITIAL_USERS['user-turkey'],
            content: 'Applications will open directly via the e-Devlet student portal starting next Monday, open to all accredited university undergraduates.',
            timestamp: '45 mins ago',
            likesCount: 182,
            isLiked: false,
          }
        ]
      },
      {
        id: 'c2',
        userId: 'user-tariq',
        user: INITIAL_USERS['user-tariq'],
        content: 'Exemplary leadership on regional peace and clean trade! Greetings from youth delegations in Pakistan 🇵🇰🤝🇹🇷',
        timestamp: '30 mins ago',
        likesCount: 95,
        isLiked: false,
      }
    ],
  },
  {
    id: 'post-pakistan-1',
    authorId: 'user-pakistan',
    author: INITIAL_USERS['user-pakistan'],
    content: 'The Government of Pakistan successfully concluded the 2026 International Economic & Digital Corridors Summit in Islamabad today. \n\nKey milestones achieved:\n• $3.2B bilateral climate resilience and clean tech infrastructure compact\n• Nationwide rollout of the "Digital Youth Enterprise" initiative offering laptops, AI training, and seed capital to 200,000 college graduates\n• Special facilitation desks established for foreign universities to partner with Pakistani colleges\n\nTogether with brotherly nations and international institutions, we are building an inclusive and sustainable future for our hardworking youth.',
    timestamp: '4 hours ago',
    createdAt: Date.now() - 4 * 60 * 60 * 1000,
    audience: 'public',
    categoryLabel: 'Prime Minister State Announcement',
    imageUrl: '/src/assets/images/pakistan_state_summit_1791116208095.jpg',
    speechDetails: {
      location: 'Prime Minister House, Islamabad',
      event: '2026 Economic & Digital Summit',
    },
    likesCount: 19800,
    userReaction: null,
    commentsCount: 980,
    sharesCount: 2410,
    hashtags: ['#PakistanRising', '#DigitalSummit', '#YouthEmpowerment', '#Diplomacy'],
    comments: [
      {
        id: 'cp-1',
        userId: 'user-lums',
        user: INITIAL_USERS['user-lums'],
        content: 'LUMS faculties and students stand eager to drive the AI training curriculums and incubation hubs for this national program.',
        timestamp: '3 hours ago',
        likesCount: 145,
        isLiked: false,
      },
      {
        id: 'cp-2',
        userId: 'user-tariq',
        user: INITIAL_USERS['user-tariq'],
        content: 'This will transform opportunities for graduates across all four provinces. Transparent merit-based delivery will be paramount!',
        timestamp: '2 hours ago',
        likesCount: 78,
        isLiked: false,
      }
    ]
  },
  {
    id: 'post-oxford-1',
    authorId: 'user-oxford',
    author: INITIAL_USERS['user-oxford'],
    content: 'We are thrilled to announce a major breakthrough in room-temperature quantum battery storage, developed jointly by our Department of Materials and international partner institutes. \n\nThis research paves the way for electric aviation and off-grid renewable energy capture at unprecedented scale. Applications for our 2026-2027 Rhodes and Clarendon International Scholarships are now open for applicants worldwide!',
    timestamp: '6 hours ago',
    createdAt: Date.now() - 6 * 60 * 60 * 1000,
    audience: 'public',
    categoryLabel: 'Academic Research & Admissions',
    imageUrl: '/src/assets/images/university_campus_graduates_1791116224809.jpg',
    news: {
      publisher: 'Oxford University Press / Nature Science',
      domain: 'ox.ac.uk/research',
      headline: 'Room-Temperature Solid Battery Storage Breakthrough Published in Nature',
      summary: 'Oxford researchers achieve 85% energy density increase in sustainable solid-state ionic storage cells.',
      url: 'https://www.ox.ac.uk/research/quantum-storage-breakthrough-2026',
      imageUrl: '/src/assets/images/university_campus_graduates_1791116224809.jpg',
    },
    likesCount: 14200,
    userReaction: 'love',
    commentsCount: 420,
    sharesCount: 1850,
    hashtags: ['#OxfordResearch', '#QuantumEnergy', '#Scholarships', '#HigherEducation'],
    comments: [
      {
        id: 'co-1',
        userId: 'user-me',
        user: INITIAL_USERS['user-me'],
        content: 'An extraordinary scientific milestone. Proud to see cross-border academic collaboration leading the clean energy transition.',
        timestamp: '5 hours ago',
        likesCount: 52,
        isLiked: false,
      }
    ]
  },
  {
    id: 'post-robotics-1',
    authorId: 'user-robotics',
    author: INITIAL_USERS['user-robotics'],
    content: 'Unveiling the Apex Orion Series: Next-generation clean automated inspection robotics for modern urban transit networks and solar arrays. \n\nBy leveraging localized edge computing and zero-latency sensors, our robots reduce maintenance downtime by 62% while operating completely autonomously 24/7.',
    timestamp: '9 hours ago',
    createdAt: Date.now() - 9 * 60 * 60 * 1000,
    audience: 'public',
    categoryLabel: 'Product Launch & Innovation',
    imageUrl: '/src/assets/images/tech_enterprise_innovation_1791116239383.jpg',
    video: {
      title: 'Apex Orion Clean Autonomous Inspection in Action (4K)',
      duration: '02:45',
      thumbnailUrl: '/src/assets/images/tech_enterprise_innovation_1791116239383.jpg',
      viewsCount: 88400,
    },
    likesCount: 8750,
    userReaction: null,
    commentsCount: 310,
    sharesCount: 920,
    hashtags: ['#Robotics', '#CleanTech', '#Automation', '#EngineeringExcellence'],
    comments: []
  },
  {
    id: 'post-tariq-1',
    authorId: 'user-tariq',
    author: INITIAL_USERS['user-tariq'],
    content: 'Huge shoutout to all 1,200+ student volunteers who joined our Youth Civic & Voter Registration Rally across five university campuses today! \n\nWhether you are a student, young entrepreneur, or first-time voter: your voice in civic decision-making shapes tomorrow’s policies. Let’s make our campuses vibrant centers of civic discussion!',
    timestamp: '12 hours ago',
    createdAt: Date.now() - 12 * 60 * 60 * 1000,
    audience: 'campus',
    categoryLabel: 'Civic Rally & Student Movement',
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1000&auto=format&fit=crop&q=80',
    likesCount: 3420,
    userReaction: 'like',
    commentsCount: 180,
    sharesCount: 340,
    hashtags: ['#YouthVoters', '#CivicEngagement', '#CampusLife', '#Democracy'],
    comments: []
  }
];

export const INITIAL_STORIES: Story[] = [
  {
    id: 'story-turkey',
    userId: 'user-turkey',
    user: INITIAL_USERS['user-turkey'],
    mediaUrl: '/src/assets/images/turkey_presidential_address_1791116189647.jpg',
    mediaType: 'image',
    caption: 'Official address to international delegations at the Presidential Complex.',
    timestamp: '1h ago',
    expiresAt: Date.now() + 23 * 3600000,
    isViewed: false,
  },
  {
    id: 'story-pakistan',
    userId: 'user-pakistan',
    user: INITIAL_USERS['user-pakistan'],
    mediaUrl: '/src/assets/images/pakistan_state_summit_1791116208095.jpg',
    mediaType: 'image',
    caption: 'Historic $3.2B bilateral climate & tech compact signed in Islamabad.',
    timestamp: '3h ago',
    expiresAt: Date.now() + 21 * 3600000,
    isViewed: false,
  },
  {
    id: 'story-oxford',
    userId: 'user-oxford',
    user: INITIAL_USERS['user-oxford'],
    mediaUrl: '/src/assets/images/university_campus_graduates_1791116224809.jpg',
    mediaType: 'image',
    caption: 'Welcome to our international scholarship scholars at the Radcliffe Quad!',
    timestamp: '4h ago',
    expiresAt: Date.now() + 20 * 3600000,
    isViewed: false,
  },
  {
    id: 'story-robotics',
    userId: 'user-robotics',
    user: INITIAL_USERS['user-robotics'],
    mediaUrl: '/src/assets/images/tech_enterprise_innovation_1791116239383.jpg',
    mediaType: 'image',
    caption: 'Live demo: Orion-6 autonomous clean grid inspection testing.',
    timestamp: '6h ago',
    expiresAt: Date.now() + 18 * 3600000,
    isViewed: false,
  },
  {
    id: 'story-lums',
    userId: 'user-lums',
    user: INITIAL_USERS['user-lums'],
    mediaUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1000&auto=format&fit=crop&q=80',
    mediaType: 'image',
    caption: 'Campus Spring Innovation Fair is live! Over 80 student startups exhibiting.',
    timestamp: '8h ago',
    expiresAt: Date.now() + 16 * 3600000,
    isViewed: true,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'speech',
    actor: INITIAL_USERS['user-turkey'],
    message: 'published a new official speech and policy address: Mediterranean Energy & Green Trade Accord.',
    timestamp: '2 hours ago',
    postId: 'post-turkey-1',
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'comment',
    actor: INITIAL_USERS['user-turkey'],
    message: 'replied to your comment on the Presidential Address: "Applications will open directly via e-Devlet..."',
    timestamp: '45 mins ago',
    postId: 'post-turkey-1',
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'news',
    actor: INITIAL_USERS['user-pakistan'],
    message: 'announced the nationwide rollout of the $3.2B Digital Youth Enterprise Initiative.',
    timestamp: '4 hours ago',
    postId: 'post-pakistan-1',
    isRead: false,
  },
  {
    id: 'notif-4',
    type: 'like',
    actor: INITIAL_USERS['user-oxford'],
    message: 'liked your perspective on international academic collaboration.',
    timestamp: '5 hours ago',
    postId: 'post-oxford-1',
    isRead: true,
  },
  {
    id: 'notif-5',
    type: 'follow',
    actor: INITIAL_USERS['user-tariq'],
    message: 'started following you on ZenSocial.',
    timestamp: '1 day ago',
    isRead: true,
  }
];

export const TRENDING_TOPICS = [
  { tag: '#DiplomaticSummit2026', count: '142K posts', category: 'Politics' },
  { tag: '#HigherEducationGrants', count: '94K posts', category: 'Education' },
  { tag: '#RenewableGridTech', count: '68K posts', category: 'Business' },
  { tag: '#TurkiyePakistanPartnership', count: '89K posts', category: 'World News' },
  { tag: '#YouthVotersForum', count: '45K posts', category: 'Civic' },
  { tag: '#QuantumStorage', count: '31K posts', category: 'Science' },
];
